# Spatial filtering

In [8]:
import numpy as np

a = [[1, 2], [3, 4]]
b = np.pad(a, (2, 4), 'symmetric')
print(b)

[[4 3 3 4 4 3 3 4]
 [2 1 1 2 2 1 1 2]
 [2 1 1 2 2 1 1 2]
 [4 3 3 4 4 3 3 4]
 [4 3 3 4 4 3 3 4]
 [2 1 1 2 2 1 1 2]
 [2 1 1 2 2 1 1 2]
 [4 3 3 4 4 3 3 4]]
